package greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.zhks.safetyproduction.entity.HiddenDBean;
import com.zhks.safetyproduction.entity.QuestionBean;

import greendao.HiddenDBeanDao;
import greendao.QuestionBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hiddenDBeanDaoConfig;
    private final DaoConfig questionBeanDaoConfig;

    private final HiddenDBeanDao hiddenDBeanDao;
    private final QuestionBeanDao questionBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hiddenDBeanDaoConfig = daoConfigMap.get(HiddenDBeanDao.class).clone();
        hiddenDBeanDaoConfig.initIdentityScope(type);

        questionBeanDaoConfig = daoConfigMap.get(QuestionBeanDao.class).clone();
        questionBeanDaoConfig.initIdentityScope(type);

        hiddenDBeanDao = new HiddenDBeanDao(hiddenDBeanDaoConfig, this);
        questionBeanDao = new QuestionBeanDao(questionBeanDaoConfig, this);

        registerDao(HiddenDBean.class, hiddenDBeanDao);
        registerDao(QuestionBean.class, questionBeanDao);
    }
    
    public void clear() {
        hiddenDBeanDaoConfig.clearIdentityScope();
        questionBeanDaoConfig.clearIdentityScope();
    }

    public HiddenDBeanDao getHiddenDBeanDao() {
        return hiddenDBeanDao;
    }

    public QuestionBeanDao getQuestionBeanDao() {
        return questionBeanDao;
    }

}
